### ISSUE TITLE
Limiting number of changes being analyzed to 10 pages

### ISSUE THREAD

**Issue by nitinramvelraj** [platisd/openai-pr-description#2]
Why is the action limited to reading 10 pages? Is there some gpt limitation causing this? Getting the url and appending .diff to it gives the entire PR diff in 1 page can't we use that as input?

**Comment by platisd** [comment]
I guess you are referring to [this](https://github.com/platisd/openai-pr-description/blob/cdd3f319043fd13ef203df001435f92a09bf7e78/autofill_description.py#L134).

From what I recall, the "10 page limit" is there to not let the size of the prompt grow too large. The prompt size will eventually be capped according to OpenAI's API limits. Each model has a different one, with currently `gpt-4.0` having the largest.

The particular approach was selected over using the raw `.diff`, since if I am not mistaken produced better results. The current format makes it more clear to the model what change belonged to which file. This was the case with `gpt-3.5-turbo` I was using at the time. `gpt-4.0` might be better but I haven't tried it out. :thinking: 

What we could do is have the "10 page limit" configurable by the user via the action and set to a different limit. What do you think?

**Comment by nitinramvelraj** [comment]
Hmm, well there is the max tokens chat gpt can take limitations (which will exist with all language models). So maybe the better approach would be to not have any limit and chunk and iteratively analyze each chunk and combine the answer in a final step? I have seen this approach used in other places

**Comment by platisd** [comment]
I recently tried this approach for [another project](https://github.com/platisd/sycophant) and I can tell you it will be expensive. 😁

Even if the PR includes more than 300 files (10 pages * 30 files per page), shouldn't the first 300 be enough to decently describe the PR?
Can you elaborate on the issue you faced?

**Comment by nitinramvelraj** [comment]
Yeah, it could be expensive. I didn't face an issue. I just liked the implementation and was wondering if this could pose a potential issue sometime. 

Realistically, it is rare for more than 300 pages to be changed.

**Comment by platisd** [comment]
I guess in theory it could produce a description that's not representative, but until someone complains about it (that's why I asked if you faced issues 😁), I'd say it's a good enough compromise.
